### ISSUE TITLE
1.1.15 to 1.1.16 update problem

### ISSUE THREAD

**Issue by lamixer** [borgbackup/homebrew-tap#11]
Hello:

This is on MacOS Catalina (I think: 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64 -- whatever that indicates, don't have console access at the moment), attempting to brew upgrade all, including borg 1.1.15 to 1.1.16. Note, this update worked fine for me on a Big Sur Intel mac a few days ago.

% brew upgrade
==> Upgrading 1 outdated package:
borgbackup/tap/borgbackup-fuse 1.1.15 -> 1.1.16
==> Upgrading borgbackup/tap/borgbackup-fuse 1.1.15 -> 1.1.16 
==> Downloading https://files.pythonhosted.org/packages/b1/d4/44443fbaac6d5b878da99e7c0948ee93
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/0266b7b5877238b28ca3a275d775c5fcb1128a2bc9200013c7c2fe752e4d0451--llfuse-1.4.1.tar.gz
==> Downloading https://github.com/borgbackup/borg/releases/download/1.1.16/borgbackup-1.1.16.
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/f0182f8b7199d1440154cdbf74620e2400b3660e842fcf717088a6a58bf422b8--borgbackup-1.1.16.tar.gz
==> python3.9 -m venv /usr/local/Cellar/borgbackup-fuse/1.1.16/libexec
==> /usr/local/Cellar/borgbackup-fuse/1.1.16/libexec/bin/pip install -v --no-deps --no-binary 
Last 15 lines from /Users/user/Library/Logs/Homebrew/borgbackup-fuse/02.pip:
  Found link https://files.pythonhosted.org/packages/9e/24/bc928987f35dd0167f21b13a1777c21b9c5917c9894cff93f1c1a6cb8f3b/pip-21.0.tar.gz#sha256=b330cf6467afd5d15f4c1c56f5c95e56a2bfb941c869bed4c1aa517bcb16de25 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0
  Found link https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl#sha256=37fd50e056e2aed635dec96594606f0286640489b0db0ce7607f7e51890372d5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz#sha256=99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.0.1
  Found link https://files.pythonhosted.org/packages/ac/cf/0cc542fc93de2f3b9b53cb979c7d1118cffb93204afb46299a9f858e113f/pip-21.1-py3-none-any.whl#sha256=ea9f2668484893e90149fd5a6124e04651ffedd67203a8aaf030d31406b937a4 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1
  Found link https://files.pythonhosted.org/packages/de/62/77b8b1a9f9c710988e5a58c22a7cd025b63b204df57a6ea939d6d39da421/pip-21.1.tar.gz#sha256=a810bf07c3723a28621c29abe8e34429fa082c337f89aea9a795865416b66d3e (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1
  Found link https://files.pythonhosted.org/packages/cd/6f/43037c7bcc8bd8ba7c9074256b1a11596daa15555808ec748048c1507f08/pip-21.1.1-py3-none-any.whl#sha256=11d095ed5c15265fc5c15cc40a45188675c239fb0f9913b673a33e54ff7d45f0 (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.1
  Found link https://files.pythonhosted.org/packages/94/b0/e10bdc8809c81796c80aa3644a8e3dc16594fb1bd68f5996929f26cad980/pip-21.1.1.tar.gz#sha256=51ad01ddcd8de923533b01a870e7b987c2eb4d83b50b89e1bf102723ff9fed8b (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.1
  Found link https://files.pythonhosted.org/packages/cd/82/04e9aaf603fdbaecb4323b9e723f13c92c245f6ab2902195c53987848c78/pip-21.1.2-py3-none-any.whl#sha256=f8ea1baa693b61c8ad1c1d8715e59ab2b93cd3c4769bacab84afcc4279e7a70e (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.2   Found link https://files.pythonhosted.org/packages/b1/44/6e26d5296b83c6aac166e48470d57a00d3ed1f642e89adc4a4e412a01643/pip-21.1.2.tar.gz#sha256=eb5df6b9ab0af50fe1098a52fd439b04730b6e066887ff7497357b9ebd19f79b (from https://pypi.org/simple/pip/) (requires-python:>=3.6), version: 21.1.2
Skipping link: not a file: https://pypi.org/simple/pip/
Given no hashes to check 167 links for project 'pip': discarding no candidates
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/local/Cellar/borgbackup-fuse/1.1.16/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Removed file:///private/tmp/borgbackup-fuse--llfuse-20210531-77068-aq26az/llfuse-1.4.1 from build tracker '/private/tmp/pip-req-tracker-gbl1nebi'
Removed build tracker: '/private/tmp/pip-req-tracker-gbl1nebi'

Error prevented borgbackup-fuse from creating the new 1.1.16 directory, so I couldn't try the indicated pip upgrade procedure.

Thanks.

**Comment by lamixer** [comment]
this could have something to do with a permission issue. For example, I cannot currently run borg --version, get zsh: permission denied: borg.

**Comment by lamixer** [comment]
OK!!! SORRY! Another bogus report from me, all is well.

**Comment by m3nu** [comment]
No worries. Glad you soled it. I got a similar error once and it went away for some reason.
