### ISSUE TITLE
Cannot install borgbackup/tap/borgbackup-fuse because conflicting formulae are installed.

### ISSUE THREAD

**Issue by pin00b** [borgbackup/homebrew-tap#5]
Sorry to bother you! Unfortunately I only have very basic Unix/CLI knowledge, so I can't solve the problem without help and don't want to "corrupt" anything... But I really want to use Vorta/Borgbase as backup solution for my productive environment!

I wasn't able to mount archives because of the known osxfuse/macFUSE issues, so I followed the instructions on this tap (```brew install --cask osxfuse && brew install borgbackup/tap/borgbackup-fuse```) after installing Vorta (```brew cask install vorta```).

Right now there's an error message:
```
Error: Cannot install borgbackup/tap/borgbackup-fuse because conflicting formulae are installed.
  borgbackup: because borgbackup-fuse is a patched version of borgbackup

Please `brew unlink borgbackup` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side effects in the
resulting software.
```

OS: macOS 11.0.1
Vorta: 0.7.1
Borgbackup: 1.1.14
Installed from: see above

Should I really perform ```brew unlink borgbackup```,``` brew install borgbackup/tap/borgbackup-fuse``` again and link in the formula I previously unlinked? - Please give me a hint to do the right steps, since I won't do the trial/error thing. Thank you so much!

**Comment by sunknudsen** [comment]
Hey @pin00b, thanks for reaching out.

I'm sure many others will have the same question (a recent upstream Homebrew [deprecation](https://github.com/borgbackup/borg/issues/5522) has made things a little confusing).

You can safely run `brew unlink borgbackup`. Let us know if that solve the issue and you can mount archives.

**Comment by m3nu** [comment]
Vorta still relies on the official `borgbackup` formula. I should remove that altogether and users need to decide which version of Borg to use (with/without FUSE).

**Comment by pin00b** [comment]
Hey @sunknudsen, many thanks for answering ultra-fast! I'm (obviously) pretty new to GitHub & Co., slowly but surely I am finding out how things work. –
Just to get a slightly deeper understanding of the necessary procedure to "reload" the deprecated support for FUSE: why is it necessary to run brew unlink borgbackup? Did I do something wrong before? Or is unlinking an unavoidable step? Then this could be included in the documentation that is still being written to give more help to inexperienced users like me. That would be great!

> You can safely run `brew unlink borgbackup`. Let us know if that solve the issue and you can mount archives.

For the moment mounting archives works, thank you! Further monitoring how things work. BTW: any (future) options to mount a whole repo via Vorta (@m3nu )? Dumb Idea?

**Comment by pin00b** [comment]
> Vorta still relies on the official `borgbackup` formula. I should remove that altogether and users need to decide which version of Borg to use (with/without FUSE).

I'm not sure if I fully understand the technical background, but it sounds very good! Go ahead 👍

**Comment by m3nu** [comment]
I've submitted a change request to remove this dependency and let the user decide instead:

https://github.com/Homebrew/homebrew-cask/pull/94586

After that we need to update the docs in multiple places.

**Comment by m3nu** [comment]
I'm closing this now, since it's not a Borg issue. Let's discuss on [Vorta's Github page](https://github.com/borgbase/vorta/issues).

> For the moment mounting archives works, thank you! Further monitoring how things work. BTW: any (future) options to mount a whole repo via Vorta (@m3nu )? Dumb Idea?

You can already mount a whole repo by not selecting any archive and just hitting "Mount".

**Comment by pin00b** [comment]
> I'm closing this now, since it's not a Borg issue. Let's discuss on [Vorta's Github page](https://github.com/borgbase/vorta/issues).
> 
> > For the moment mounting archives works, thank you! Further monitoring how things work. BTW: any (future) options to mount a whole repo via Vorta (@m3nu )? Dumb Idea?
> 
> You can already mount a whole repo by not selecting any archive and just hitting "Mount".

I see. – Thank you so much! Excuse me for being so undisciplined/confused about threads/issues/questions/bugs etc. I promise to get better. Really love your work, keep going!

**Comment by m3nu** [comment]
Thanks, no worries.

**Comment by sunknudsen** [comment]
@pin00b Exploring the rabbit hole is challenging… so many new concepts to learn… rewiring one’s mind. Congrats for having the courage to learn this stuff and ask for help.
